Implement local cache for crowdsec
fbonalair/traefik-crowdsec-bouncer pull request #33
Opened 2022-09-18 18:06 UTC by maxlerebourg

https://github.com/fbonalair/traefik-crowdsec-bouncer/pull/32 
With better implementation

3 mode:
- stream mode: use /decisions/stream to get in cache the decisions.
- live mode: like before but with cached response from crowdsec
- none mode: like before (every request ask crowdsec)

2022-09-18 20:23 UTC, fbonalair requested changes
Thank you a lot for the work !    
Excellent idea for the go routine around the cache.   
I added some quality of life comments around, feel free to check them out.

On more major note though is in the steam mode: make the server fail in case of error. For the bouncer I took a very defensive approach - it's a security component after all - we don't want a bouncer that is allowing any request because we couldn't update the cache so **[fail-fast](https://en.wikipedia.org/wiki/Fail-fast)**. Thanks to you, user have other mode as fallback if they can't found/fix the issue.   
For that in the function HandleStreamCache, you have a lot of returns in case of error but without handling them. In those case Panic with a descriptive log and make the whole bouncer fail.

2022-09-18 20:23 UTC, fbonalair commented on controler/controler.go
>  func Healthz(c *gin.Context) {
Adding cache to our service break it's statelessness, it should be reflected in this probe.   
Could you implement something like "In stream mode, while the go routine HandleStreamCache hasn't successfully completed a run, this route return a HTTP 503".

2022-09-19 13:24 UTC, maxlerebourg commented on controler/controler.go
> +			cache.Set(key, []byte("f"), int(crowdsecBouncerDefaultCacheDuration.Seconds()))
Crowdsec can response with duration value when the IP is authorized ?

2022-09-19 13:38 UTC, maxlerebourg commented
Hey, thanks for choosing my MR, the other one is made by a friend. We have a different approach to it, so you can go look at it too.
I have fixed all the issues you brought up, but one of them is not understandable to me.

Another point about the 403 return in case of the cache stream update fail. In your previous comment, you said "crash the bouncer" and in you PR comment "return 403 on /healthz", I choose the second, feel free to tell me the opposite was the good answer.

2023-04-25 13:25 UTC, closed without merging